# Generated by Django 5.0 on 2023-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('image_file', models.ImageField(blank=True, default='uploads/image.png', null=True, upload_to='uploads/')),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
