# Generated by Django 4.2.1 on 2023-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('is_admin', models.BooleanField(default=False)),
                ('image_file', models.CharField(max_length=300)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
