# Generated by Django 4.2.1 on 2023-06-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
