# Generated by Django 4.2.1 on 2023-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_file',
            field=models.ImageField(blank=True, default='uploads/image.png', null=True, upload_to='uploads/'),
        ),
    ]
