# Generated by Django 5.0 on 2023-12-26 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 15, 9, 38, 171970)),
        ),
    ]
