# Generated by Django 4.2.1 on 2023-06-05 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 8, 42, 48, 784142)),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='loan_status',
            field=models.BooleanField(default=True),
        ),
    ]
