# Generated by Django 4.2.1 on 2023-06-05 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookinstance_due_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 15, 3, 5, 1641)),
        ),
    ]
