# Generated by Django 4.2.1 on 2023-06-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 13, 4, 16, 114428)),
        ),
    ]
