# Generated by Django 4.1.7 on 2023-06-06 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_bookinstance_due_back_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 13, 33, 22, 845003)),
        ),
    ]
