# Generated by Django 4.2.1 on 2023-06-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_book_title_alter_bookinstance_due_back'),
        ('book', '0014_alter_bookinstance_due_back'),
    ]

    operations = [
    ]
