# Generated by Django 5.0 on 2023-12-23 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_merge_20230606_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 9, 1, 6, 286309)),
        ),
    ]
