# Generated by Django 5.0 on 2023-12-23 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 10, 59, 27, 774148)),
        ),
    ]
